
const router = require('express').Router();
const surfSpots = [
    {
      surf_spot: 'Ocean Beach',
      location: 'San Francisco, CA',
      type: 'Beach - sand bottom with shifting peaks',
      optimal_swell_direction: 'NW, W, SW',
      optimal_wind: 'light to none - up to 10mph NE',
      optimal_swell_size: 'Waist high to double-overhead (note: can handle much bigger but becomes impossible to paddle out)',
      optimal_tide: 'All-tides',
    },
    {
      surf_spot: 'Mavericks',
      location: 'Half Moon Bay, CA',
      type: 'Reef - rock bottom',
      optimal_swell_direction: 'NW, W, SW',
      optimal_wind: 'light to none - up to 10mph NE',
      optimal_swell_size: 'Minimum size triple overhead.  Can handle and routinely sees days up to 5-6x overhead',
      optimal_tide: 'Low to Mid',
    },
    {
        surf_spot: 'Malibu',
        location: 'Malibu, CA',
        type: 'Point - Sand Bottom',
        optimal_swell_direction: 'S, SW, WSW',
        optimal_wind: 'N, NW',
        optimal_swell_size: 'Waist High to Double Overhead',
        optimal_tide: 'Mid',
      },
      {
        surf_spot: 'The Wedge',
        location: 'Newport Beach, CA',
        type: 'Beach - Sand Bottom',
        optimal_swell_direction: 'SW, SSW, S, SSE',
        optimal_wind: 'NE, E, SE',
        optimal_swell_size: 'Double overhead to 5x overhead',
        optimal_tide: 'Low to Mid',
      },
      {
        surf_spot: 'Pismo Beach Pier',
        location: 'Pismo Beach, CA',
        type: 'Reef - rock bottom',
        optimal_swell_direction: 'Shorter period W or NW or long period SW',
        optimal_wind: 'E, NE, or none',
        optimal_swell_size: 'Waist high to overhead',
        optimal_tide: 'Low to Mid',
      },
      {
        surf_spot: 'Rincon',
        location: 'Santa Barbara, CA',
        type: 'Point / Rivermouth - cobblestone',
        optimal_swell_direction: 'W, WSW, WNW',
        optimal_wind: 'N, NE',
        optimal_swell_size: 'Head high to double overhead',
        optimal_tide: 'Low',
      },
      {
        surf_spot: 'Mavericks',
        location: 'Half Moon Bay',
        type: 'Reef - rock bottom',
        optimal_swell_direction: 'NW, W, SW',
        optimal_wind: 'light to none - up to 10mph NE',
        optimal_swell_size: 'Minimum size triple overhead.  Can handle and routinely sees days up to 5-6x overhead',
        optimal_tide: 'Low to Mid',
      },
      {
        surf_spot: 'Mavericks',
        location: 'Half Moon Bay',
        type: 'Reef - rock bottom',
        optimal_swell_direction: 'NW, W, SW',
        optimal_wind: 'light to none - up to 10mph NE',
        optimal_swell_size: 'Minimum size triple overhead.  Can handle and routinely sees days up to 5-6x overhead',
        optimal_tide: 'Low to Mid',
      },
      {
        surf_spot: 'Mavericks',
        location: 'Half Moon Bay',
        type: 'Reef - rock bottom',
        optimal_swell_direction: 'NW, W, SW',
        optimal_wind: 'light to none - up to 10mph NE',
        optimal_swell_size: 'Minimum size triple overhead.  Can handle and routinely sees days up to 5-6x overhead',
        optimal_tide: 'Low to Mid',
      },
      {
        surf_spot: 'Mavericks',
        location: 'Half Moon Bay',
        type: 'Reef - rock bottom',
        optimal_swell_direction: 'NW, W, SW',
        optimal_wind: 'light to none - up to 10mph NE',
        optimal_swell_size: 'Minimum size triple overhead.  Can handle and routinely sees days up to 5-6x overhead',
        optimal_tide: 'Low to Mid',
      },
      {
        surf_spot: 'Mavericks',
        location: 'Half Moon Bay',
        type: 'Reef - rock bottom',
        optimal_swell_direction: 'NW, W, SW',
        optimal_wind: 'light to none - up to 10mph NE',
        optimal_swell_size: 'Minimum size triple overhead.  Can handle and routinely sees days up to 5-6x overhead',
        optimal_tide: 'Low to Mid',
      },
      {
        surf_spot: 'Mavericks',
        location: 'Half Moon Bay',
        type: 'Reef - rock bottom',
        optimal_swell_direction: 'NW, W, SW',
        optimal_wind: 'light to none - up to 10mph NE',
        optimal_swell_size: 'Minimum size triple overhead.  Can handle and routinely sees days up to 5-6x overhead',
        optimal_tide: 'Low to Mid',
      },
      {
        surf_spot: 'Mavericks',
        location: 'Half Moon Bay',
        type: 'Reef - rock bottom',
        optimal_swell_direction: 'NW, W, SW',
        optimal_wind: 'light to none - up to 10mph NE',
        optimal_swell_size: 'Minimum size triple overhead.  Can handle and routinely sees days up to 5-6x overhead',
        optimal_tide: 'Low to Mid',
      },
      {
        surf_spot: 'Mavericks',
        location: 'Half Moon Bay',
        type: 'Reef - rock bottom',
        optimal_swell_direction: 'NW, W, SW',
        optimal_wind: 'light to none - up to 10mph NE',
        optimal_swell_size: 'Minimum size triple overhead.  Can handle and routinely sees days up to 5-6x overhead',
        optimal_tide: 'Low to Mid',
      },
      {
        surf_spot: 'Mavericks',
        location: 'Half Moon Bay',
        type: 'Reef - rock bottom',
        optimal_swell_direction: 'NW, W, SW',
        optimal_wind: 'light to none - up to 10mph NE',
        optimal_swell_size: 'Minimum size triple overhead.  Can handle and routinely sees days up to 5-6x overhead',
        optimal_tide: 'Low to Mid',
      },

  ];
  
  
  
  module.exports = router;